# 1.0
insert into ods_policy_insured_detail
select
UUID() as id,
a.id as insured_id,
a.policy_id,
a.insured_type,
a.is_legal,
a.`name` as insured_name,
a.gender as insured_gender,
a.cert_type as insured_cert_type,
a.cert_no as insured_cert_no,
a.birthday as insured_birthday,
a.profession as insured_profession,
a.mobile as insured_mobile,
a.industry as insured_industry,
a.work_type as insured_work_type,
a.nation as insured_nation,
a.company_name as insured_company_name,
a.company_phone as insured_company_phone,
a.is_chief_insurer,
a.status as insured_status,
a.insure_policy_status,
a.create_time as insured_create_time,
a.update_time as insured_update_time,
a.start_date as insured_start_date,
a.end_date as insured_end_date,
b.id as child_id,
b.child_name,
b.child_gender,
b.child_cert_type,
b.child_cert_no,
b.child_birthday,
b.child_nationality,
b.child_policy_status,
b.start_date as child_start_date,
b.end_date as child_end_date,
b.create_time as child_create_time,
if(length(a.cert_no)=18,round(TIMESTAMPDIFF(day, substr(a.cert_no,7,8), a.start_date)/365),-1) as age
from odr_policy_insured a
left join odr_policy_insured_child b on a.id=b.insured_id
left join odr_policy c on a.policy_id=c.id
where (c.user_id not in ('10100080492') or c.user_id is null) and (a.remark not in ('obsolete') or a.remark is null);

insert into ods_policy_insured_detail
select
UUID() as id,
a.id as insured_id,
a.policy_id,
a.insured_type,
a.is_legal,
a.`name` as insured_name,
a.gender as insured_gender,
a.cert_type as insured_cert_type,
a.cert_no as insured_cert_no,
a.birthday as insured_birthday,
a.profession as insured_profession,
a.mobile as insured_mobile,
a.industry as insured_industry,
a.work_type as insured_work_type,
a.nation as insured_nation,
a.company_name as insured_company_name,
a.company_phone as insured_company_phone,
a.is_chief_insurer,
a.status as insured_status,
a.insure_policy_status,
a.create_time as insured_create_time,
a.update_time as insured_update_time,
a.start_date as insured_start_date,
a.end_date as insured_end_date,
b.id as child_id,
b.child_name,
b.child_gender,
b.child_cert_type,
b.child_cert_no,
b.child_birthday,
b.child_nationality,
b.child_policy_status,
b.start_date as child_start_date,
b.end_date as child_end_date,
b.create_time as child_create_time,
if(length(a.cert_no)=18,round(TIMESTAMPDIFF(day, substr(a.cert_no,7,8), a.start_date)/365),-1) as age
from odr_policy_insured a
left join odr_policy_insured_child b on a.id=b.insured_id
left join odr_policy c on a.policy_id=c.id
where c.insure_code in ('15000001') and c.policy_code like 'BZN%';

#2.0
insert into ods_policy_insured_detail
select
UUID() as id,
a.id as insured_id,
c.id as policy_id,
'' as insured_type,
a.is_legal,
a.`name` as insured_name,
a.sex as insured_gender,
a.cert_type as insured_cert_type,
a.cert_no as insured_cert_no,
a.birthday as insured_birthday,
a.profession_code as insured_profession,
a.tel as insured_mobile,
a.industry_code as insured_industry,
a.work_type as insured_work_type,
a.nation as insured_nation,
a.company_name as insured_company_name,
a.company_phone as insured_company_phone,
'1' as is_chief_insurer,
case when a.`status`='1' then '0' else '1' end as insured_status,
case when (a.`status`='1' and a.end_date>now() and a.start_date<now()) then '1' else '2' end as insure_policy_status,
a.create_time as insured_create_time,
a.update_time as insured_update_time,
a.start_date as insured_start_date,
a.end_date as insured_end_date,
b.id as child_id,
b.`name` as child_name,
b.sex as child_gender,
b.cert_type as child_cert_type,
b.cert_no as child_cert_no,
b.birthday as child_birthday,
b.nation as child_nationality,
case when b.`status`='1' then '1' else '2' end as child_policy_status,
b.start_date as child_start_date,
b.end_date as child_end_date,
b.create_time as child_create_time,
case when a.cert_type='1' then if(length(a.cert_no)=18,round(TIMESTAMPDIFF(day, substr(a.cert_no,7,8), a.start_date)/365),-1) else null end as age
from b_policy_subject_person_master a
left join b_policy_subject_person_slave b on a.policy_no=b.policy_no
left join b_policy c on a.policy_no=c.policy_no;